//! Prelude module - commonly used imports

pub use crate::core::{
    Color,
    Element,
    ElementId,
    Style,
    FlexDirection,
    AlignItems,
    JustifyContent,
    Display,
    Position,
    Overflow,
    TextWrap,
    BorderStyle,
};

pub use crate::components::{
    Box,
    Text,
    Span,
    Line,
    Newline,
    Spacer,
    Transform,
    Static,
    static_output,
    List,
    ListItem,
    ListState,
    Table,
    Row,
    Cell,
    TableState,
    Constraint,
    Scrollbar,
    ScrollbarSymbols,
    Tabs,
    Tab,
    Progress,
    ProgressSymbols,
    Gauge,
    Sparkline,
    BarChart,
    Bar,
};

pub use crate::renderer::render;

pub use crate::hooks::{
    use_signal,
    use_effect,
    use_input,
    use_app,
    use_focus,
    use_focus_manager,
    use_stdin,
    use_stdout,
    use_stderr,
    use_measure,
    measure_element,
    use_mouse,
    Signal,
    Key,
    AppContext,
    FocusState,
    FocusManagerHandle,
    UseFocusOptions,
    StdinHandle,
    StdoutHandle,
    StderrHandle,
    Dimensions,
    MeasureRef,
    use_is_screen_reader_enabled,
    Mouse,
    MouseAction,
    MouseButton,
    use_scroll,
    ScrollState,
    ScrollHandle,
    use_window_title,
    use_window_title_fn,
    set_window_title,
};
